[0m17:16:27.781238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f04055220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f0282da00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f026e8a00>]}


============================== 17:16:27.783630 | ed98c2e5-18d5-4bfc-956b-79fde941ffae ==============================
[0m17:16:27.783630 [info ] [MainThread]: Running with dbt=1.8.7
[0m17:16:27.784137 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/tunguyenn99/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init dbt_youtube', 'send_anonymous_usage_stats': 'True'}
[0m17:16:27.798839 [debug] [MainThread]: Starter project path: /home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/include/starter_project
[0m17:16:27.805486 [info ] [MainThread]: 
Your new dbt project "dbt_youtube" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:16:27.805906 [info ] [MainThread]: Setting up your profile.
[0m17:16:34.713007 [error] [MainThread]: Encountered an error:

[0m17:16:34.719270 [error] [MainThread]: Traceback (most recent call last):
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/task/init.py", line 262, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/dbt/task/init.py", line 243, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/home/tunguyenn99/.local/lib/python3.8/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:16:34.721021 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 7.0035615, "process_user_time": 1.00097, "process_kernel_time": 0.093067, "process_mem_max_rss": "92204", "process_in_blocks": "52632", "process_out_blocks": "72", "command_success": false}
[0m17:16:34.721436 [debug] [MainThread]: Command `dbt init` failed at 17:16:34.721352 after 7.00 seconds
[0m17:16:34.721729 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f04055220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f04bfea60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f02616be0>]}
[0m17:16:34.722033 [debug] [MainThread]: Flushing usage events
[0m17:16:57.337100 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0dc11ad2e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0dbf97c910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0dbf97c850>]}


============================== 17:16:57.339644 | 0ec00b4a-9923-4c67-8ee5-97030fdbb71f ==============================
[0m17:16:57.339644 [info ] [MainThread]: Running with dbt=1.8.7
[0m17:16:57.340160 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/tunguyenn99/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init dbt_youtube', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:16:57.344589 [info ] [MainThread]: A project called dbt_youtube already exists here.
[0m17:16:57.345130 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.054068603, "process_user_time": 0.846247, "process_kernel_time": 0.049779, "process_mem_max_rss": "91960", "process_out_blocks": "16", "process_in_blocks": "0"}
[0m17:16:57.345462 [debug] [MainThread]: Command `dbt init` succeeded at 17:16:57.345390 after 0.05 seconds
[0m17:16:57.345713 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0dc11ad2e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0dc04438e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0dbf84d1c0>]}
[0m17:16:57.345962 [debug] [MainThread]: Flushing usage events
[0m21:06:58.423031 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77ffabf04250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77ffab217dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77ffaba55460>]}


============================== 21:06:58.426823 | 77006840-2663-47c7-bd1d-ef81bd7f0928 ==============================
[0m21:06:58.426823 [info ] [MainThread]: Running with dbt=1.8.7
[0m21:06:58.427597 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/tunguyenn99/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:06:58.428352 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/tunguyenn99/project-vscode/son-tung-mtp-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:06:58.430131 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0731818, "process_user_time": 1.22218, "process_kernel_time": 0.17347, "process_mem_max_rss": "79792", "process_in_blocks": "35496", "process_out_blocks": "8", "command_success": false}
[0m21:06:58.430699 [debug] [MainThread]: Command `dbt run` failed at 21:06:58.430537 after 0.07 seconds
[0m21:06:58.431146 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77ffabf04250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77ffa97817c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77ffa9744250>]}
[0m21:06:58.431598 [debug] [MainThread]: Flushing usage events
[0m23:14:43.460534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x768e8b313220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x768e889fd790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x768e89677280>]}


============================== 23:14:43.467102 | 5e622949-dd51-412d-a0e7-0ed79d015020 ==============================
[0m23:14:43.467102 [info ] [MainThread]: Running with dbt=1.8.7
[0m23:14:43.468149 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/tunguyenn99/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run -s g_video_rankings.sql', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:14:43.468713 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/tunguyenn99/project-vscode/son-tung-mtp-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:14:43.471050 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08517258, "process_user_time": 1.332175, "process_kernel_time": 0.177886, "process_mem_max_rss": "79660", "process_in_blocks": "49208", "process_out_blocks": "8", "command_success": false}
[0m23:14:43.471842 [debug] [MainThread]: Command `dbt run` failed at 23:14:43.471570 after 0.09 seconds
[0m23:14:43.472310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x768e8b313220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x768e88b87760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x768e8964f520>]}
[0m23:14:43.472768 [debug] [MainThread]: Flushing usage events
[0m00:46:32.719973 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x771d1cf5b1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x771d1a51a2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x771d1a50af40>]}


============================== 00:46:32.726956 | 15dc93c7-add1-4b1d-b767-1b6df03c632c ==============================
[0m00:46:32.726956 [info ] [MainThread]: Running with dbt=1.8.7
[0m00:46:32.727901 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/tunguyenn99/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -s g_video_ranking.sql', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:46:32.728694 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/tunguyenn99/project-vscode/son-tung-mtp-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:46:32.731209 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.1009881, "process_user_time": 1.879294, "process_kernel_time": 0.409741, "process_mem_max_rss": "79664", "process_in_blocks": "48944", "process_out_blocks": "16", "command_success": false}
[0m00:46:32.732005 [debug] [MainThread]: Command `dbt run` failed at 00:46:32.731820 after 0.10 seconds
[0m00:46:32.732490 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x771d1cf5b1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x771d1a50afa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x771d1a4d06d0>]}
[0m00:46:32.733168 [debug] [MainThread]: Flushing usage events
